##
## this version of docker-compose can be used up to version 1.6.n of docker-compose (docker 1.10.n+)
##

version: '2'
services:

  #
  # [ bitbucket main container ]
  #
  #  - bitbucket app
  #  - bitbucket mysql
  #  - bitbucket mysql-data
  #
  bitbucket:
    # -- sample cpu configuration for 8 core linux system (using cpu 1-4, 75% max payload, priority 640)
    # cpu_shares: 640
    # cpu_quota: 75000
    # cpuset: '0-3'
    container_name: df-atls-bitbucket-app
    build:
      context: ./df-atls-bitbucket

    depends_on:
      - bitbucket_mysql

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app

    # open gates for stash ssh port 7999
    ports:
      - "7999:7999"

    networks:
      - atlassian
      - default

  bitbucket_mysql:
    # -- sample cpu configuration for 8 core linux system (using cpu 4-5, 33% max payload, priority 256)
    # cpu_shares: 256
    # cpu_quota: 33000
    # cpuset: '3,4'
    container_name: df-atls-bitbucket-mysql
    build: 
      context: ./df-atls-bitbucket-mysql

    depends_on:
      - bitbucket_mysql_data

    extends:
      file: ./df-atls-bitbucket-mysql/compose.yml
      service: mysql

    networks:
      - atlassian

  bitbucket_mysql_data:
    container_name: df-atls-bitbucket-mysql-data
    build: 
      context: ./df-atls-bitbucket-mysql

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app_data

    entrypoint: /bin/echo "data-only container for bitbucket mysql"

  #
  # [ confluence main container ]
  #
  #  - confluence app
  #  - confluence mysql
  #  - confluence mysql-data
  #
  confluence:
    # -- sample cpu configuration for 8 core linux system (using cpu 1-4, 95% max payload, priority 896)
    # cpu_shares: 896
    # cpu_quota: 95000
    # cpuset: '0-3'
    container_name: df-atls-confluence-app
    build: 
      context: ./df-atls-confluence

    depends_on:
      - confluence_mysql

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app

    networks:
     - atlassian
     - default

  confluence_mysql:
    # -- sample cpu configuration for 8 core linux system (using cpu 4-5, 33% max payload, priority 256)
    # cpu_shares: 256
    # cpu_quota: 33000
    # cpuset: '3,4'
    container_name: df-atls-confluence-mysql
    build: ./df-atls-confluence-mysql

    depends_on:
      - confluence_mysql_data

    extends:
      file: ./df-atls-confluence-mysql/compose.yml
      service: mysql

    volumes_from:
      - confluence_mysql_data:rw

    networks:
      - atlassian

  confluence_mysql_data:
    container_name: df-atls-confluence-mysql-data
    build: 
      context: ./df-atls-confluence-mysql

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app_data

    entrypoint: /bin/echo "data-only container for confluence mysql"

  #
  # [ jira main container ]
  #
  #  - jira app
  #  - jira mysql
  #  - jira mysql-data
  #
  jira:
    # -- sample cpu configuration for 8 core linux system (using cpu 1-4, 85% max payload, priority 768)
    # cpu_shares: 768
    # cpu_quota: 85000
    # cpuset: '0-3'
    container_name: df-atls-jira-app
    build: 
      context: ./df-atls-jira

    depends_on:
      - jira_mysql

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app

    networks:
      - atlassian
      - default

  jira_mysql:
    # -- sample cpu configuration for 8 core linux system (using cpu 4-5, 33% max payload, priority 256)
    # cpu_shares: 256
    # cpu_quota: 33000
    # cpuset: '3,4'
    container_name: df-atls-jira-mysql
    build: 
      context: ./df-atls-jira-mysql

    depends_on:
      - jira_mysql_data

    extends:
      file: ./df-atls-jira-mysql/compose.yml
      service: mysql

    volumes_from:
      - jira_mysql_data:rw

    networks:
      - atlassian

  jira_mysql_data:
    container_name: df-atls-jira-mysql-data
    build: 
      context: ./df-atls-jira-mysql

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app_data

    entrypoint: /bin/echo "data-only container for jira mysql"

  #
  # [ nginx proxy main container ]
  #
  #  - nginx
  #
  nginx:
    # -- sample cpu configuration for 8 core linux system (using cpu #8, 85% max payload, priority 512)
    # cpu_shares: 512
    # cpu_quota: 85000
    # cpuset: '7'
    container_name: df-atls-nginx-proxy
    build: 
      context: ./df-atls-nginx-proxy

    extends:
      file: ./df-atls-base/compose-base.yml
      service: app

    ports:
      - "80:80"
      - "443:443"

    networks:
      - default

#
# [ networks definition for atlassian and our (other) proxy services ]
#
networks:
  default:
    driver: bridge
  atlassian:
    driver: bridge