#
# docker compose file for our atlassian product workbench. the following products will be handled by this build:
#
# - atlassian confluence (v5.9.3), main app container
#
# * confluence.host
# * confluence.mysql
#
# : confluence
# : confluence_data
# : confluence_mysql
# : confluence_mysql_data
#
# @copyright (c) 2015 dunkelfrosch, patrick.paechnatz@gmail.com,
# @version 1.0.0
#

# [confluence main container] ------------------------------------------------------------------------------------------
confluence:
  container_name: df-atls-confluence-app
  build: .

  extends:
    file: ../df-atls-base/compose-base.yml
    service: app

  ports:
    - "8090:8090"

  links:
    - confluence_mysql:confluence.mysql

  # volumes_from:
  #  - confluence_data:rw

# [confluence data container] ------------------------------------------------------------------------------------------
confluence_data:
  container_name: df-atls-confluence-app-data
  build: .

  extends:
    file: ../df-atls-base/compose-base.yml
    service: app-data

  entrypoint: /bin/echo "data-only container for confluence"

# [confluence mysql service container] ---------------------------------------------------------------------------------
confluence_mysql:
  container_name: df-atls-confluence-mysql
  build: ../df-atls-confluence-mysql

  extends:
    file: ../df-atls-confluence-mysql/compose.yml
    service: mysql

  # volumes_from:
  #  - confluence_mysql_data:rw

# [confluence mysql data container] ------------------------------------------------------------------------------------
confluence_mysql_data:
  container_name: df-atls-confluence-mysql-data
  build: ../df-atls-confluence-mysql

  extends:
    file: ../df-atls-base/compose-base.yml
    service: app-data

  entrypoint: /bin/echo "data-only container for confluence mysql"