#
# docker compose file for our atlassian product workbench. the following products will be handled by this build:
#
# - mysql (v5.6.n), bitbucket service container
#
# @copyright (c) 2015-2016 dunkelfrosch, patrick.paechnatz@gmail.com,
# @version 1.0.0
#
# [confluence mysql main container] -----------------------------------------------------------------------------------
version: '2'
services:
  mysql:
    container_name: df-atls-bitbucket-mysql
    build:
      context: .

    extends:
      file: ../df-atls-base/compose-base.yml
      service: app

    environment:
      MYSQL_DATABASE: 'bitbucket'
      MYSQL_ROOT_PASSWORD: 'please-change-me'
