#
# docker compose file for our atlassian product workbench. the following products will be handled by this build:
#
# - atlassian jira (v7.0.2), main app container
#
# * jira.host
# * jira.mysql
#
# : jira
# : jira_data
# : jira_mysql
# : jira_mysql_data
#
# @copyright (c) 2015 dunkelfrosch, patrick.paechnatz@gmail.com,
# @version 1.0.0
#

# [jira main container] ------------------------------------------------------------------------------------------
jira:
  container_name: df-atls-jira-app
  build: .

  extends:
    file: ../df-atls-base/compose-base.yml
    service: app

  ports:
    - "8080:8080"

  links:
    - jira_mysql:jira.mysql

  volumes_from:
    - jira_data:rw

# [jira data container] ------------------------------------------------------------------------------------------
jira_data:
  container_name: df-atls-jira-app-data
  build: .

  extends:
    file: ../df-atls-base/compose-base.yml
    service: app-data

  entrypoint: /bin/echo "data-only container for jira"

# [jira mysql service container] ---------------------------------------------------------------------------------
jira_mysql:
  container_name: df-atls-jira-mysql
  build: ../df-atls-jira-mysql

  extends:
    file: ../df-atls-jira-mysql/compose.yml
    service: mysql

  volumes_from:
    - jira_mysql_data:rw

# [jira mysql data container] ------------------------------------------------------------------------------------
jira_mysql_data:
  container_name: df-atls-jira-mysql-data
  build: ../df-atls-jira-mysql

  extends:
    file: ../df-atls-base/compose-base.yml
    service: app-data

  entrypoint: /bin/echo "data-only container for jira mysql"
